### PR TITLE
Fixes #88: Added state to track hydration (test failing)

### LINKED ISSUE #88: Any way to know if hydrate() returns static or hydrated content ?
Hello,

Firstly, thank you for the awesome tool. I have been using this to build my personal blog and really happy with the results.

However there is a very very small issue.
As per the README, at [line 108 commit: 797f471, branch: master](https://github.com/hashicorp/next-mdx-remote/master/README.md#L108), static content would be rendered until hydration has finished.

Is there a way to know this state change?
Can we return a `isLoading` property for the `hydrate()` hook, which becomes `false` when the content has been hydrated.
Is it possible?

Consider the case when the typography is unconventional and FOIT would be preferred over FOUT.
In my case I am using tailwindcss which removes the default h1..h6 styles and the static content looks like a <p> tag. After hydration the css styles apply and make the h1...h6 tags look big and bold. This change isn't pleasant at all.

Thank you for reading through!

### PR DESCRIPTION
**Pull request by dipunj**
@jescalan I tried comprehending the tests, but couldn't get the test working.
The following test is failing: **rehydrates correctly in browser**

The changes are very trivial IMHO, but I couldn't debug the failed test even after trying a lot. Could you please help me understand why could it be failing?

### CODE REVIEW

**Comment by jescalan** [comment]
Happy to help with this, I'll pull it down and take a look this week

**Comment by dipunj** [comment]
Hey @jescalan, I see that the tests had been updated. I have pulled in the changes from the main branch. All the tests are now passing. I have also tested in my personal blog, and it is working fine.

Could you please review the PR someday this week ?

Happy to fix any errors on my end. Thanks!

**Comment by jescalan** [comment]
@dipunj - sounds great - it looks like we have conflicts, could you rebase on top of the `main` branch? this should also trigger a circleci run for you, i just enabled it to run in forks

**Comment by dipunj** [comment]
Hey @jescalan - I have rebased onto main branch of `git@github.com:hashicorp/next-mdx-remote.git`.
Thank you for the Circle CI tests.

Both the hydration tests are failing again. Could you please help me debug it.

Really appreciate your help.

**Comment by jescalan** [comment]
I'm so sorry, I just don't have time to help with this over the next few weeks due to work and personal responsibilities stacking up. Perhaps someone else can jump in, otherwise I'll get to it as soon as I can.

**Comment by dipunj** [comment]
Hey @jescalan I understand. It's not urgent, take as long as you want.

**Comment by BRKalow** [comment]
Hi @dipunj, as of [`v3.0.0`](https://github.com/hashicorp/next-mdx-remote/releases/tag/3.0.0) the MDX should now hydrate synchronously by default, as you would expect with any other SSR'd components. As a result, I don't think this change will be needed. Thanks for your contribution, and please feel free to re-open the issue if you feel this is still a feature that you want!

**Pull request closed without merging**
