### PR TITLE
Allow the customization of standard markdown elements

### LINKED ISSUE #4: Replacing standard markdown elements doesn't work
If I set the components to target standard markdown html elements, like h1, img etc. 

e.g.
```
const components = {
  h1: (props) => <h1 style={{ color: 'tomato' }} {...props} />,
}
```

Then the static files are correct.

But, on page load in the browser. I think the component assignment is ignored.

With my example I'll see a red h1 for a second then black.

Html source has this in it `<h1 style="color:tomato">Games</h1>` ... `mdx(\"h1\", null, \"Games\"),`

Expected behaviour - consistent components across static and in browser.

Thanks - Davey

### PR DESCRIPTION
**Pull request by rafaelalmeidatk**
This change allows the standard makdown elements to be customized with the `components` object

Fixes #4

### CODE REVIEW

**Comment by brandonpittman** [comment]
That CLA is a little scary.

**Comment by jescalan** [comment]
Hi @brandonpittman - what about it did you find scary? I can certainly take that feedback to the right people!

**Comment by jescalan** [comment]
This is so awesome, thank you for the contribution @rafaelalmeidatk! 🎉

**Comment by brandonpittman** [comment]
@jescalan The content isn't necessarily scary, just that I've never encountered an agreement like that when looking at OSS commits. Pay no mind to me.

**Comment by jescalan** [comment]
@brandonpittman Ah ok - [we have a page here](https://www.hashicorp.com/cla) that explains a little more context around it and breaks down the legalese to plain english. There are many other major open source projects, a variety listed on the linked page that also require CLAs. Webpack is another good example of a project that we all use that [requires one](https://cla.js.foundation/webpack/webpack.js.org) 😀

**Pull request merged**
