### PR TITLE
Refactor hydrate and renderToString

### PR DESCRIPTION
**Pull request by lfades**
`renderToString` will now return the code required to render MDX in the page, instead of the code, html, and scope.

```ts
renderToString(source: string, { mdxOptions })
```

`hydrate` Will now render the MDX instead of the HTML, and it's the one receiving the scope now.

```js
hydrate(source: string, { components, ...props }, { scope })
```

@jescalan This is not backwards compatible due to `hydrate` requiring the scope instead of `renderToString`. I also don't think it's ready for merge until the new API is decided. Let me know what do you think about these changes, I've updated the tests 👍 

Something else to keep in mind:

- Imports are kind of supported, having an import won't make the mdx file break (maybe that's not good?), and if the imported component is used somewhere you could include it in `components` and it would work.
- Having a layout is supported properly now.

### CODE REVIEW

**Comment by Ehesp** [comment]
Is this PR usable? Really keen to get in-file exported components working. Happy to swap over and give it a go.

**Comment by Ehesp** [comment]
@lfades Just tried the PR, see https://github.com/hashicorp/next-mdx-remote/issues/58#issuecomment-728960467 for an error which is thrown using it

**Comment by lfades** [comment]
@Ehesp Can you try it using the docs in the updated readme? 🙏 the description is out of date as the PR is now replacing the current methods with new ones. Meaning this PR is now a refactor with breaking changes.

**Comment by Ehesp** [comment]
Hmm thought I did, although I'll try again. I'll make a minimal repro incase it's my setup 👍

**Comment by Ehesp** [comment]
@lfades Here's a minimal repro: https://github.com/Ehesp/repro-next-mdx-remote

Run `npm run dev` and load the index page:

```
SyntaxError: Unexpected token export
    at Function (<anonymous>)
    at MdxRemote (/Users/../Documents/Code/delete/mdx-rendering/node_modules/next-mdx-remote/mdx-remote.js:12:31)
```

**Comment by Ehesp** [comment]
Also worth noting this did fix a very hidden issue in my setup. When wrapping the `hydrate` function (from current code) in my own React context, the actual server rendered output did not use the context values from the parent - they were always the "default" values. Changing to this branch solved that issue. Not the best explanation but this setup is much better.

**Comment by lfades** [comment]
@Ehesp Thanks for the repro! Looks like the mdx in your repro is using `export`, which similarly to `import`, depends on a file path. `export` wasn't working before and it's not going to work with this PR either (and that's intentional). It's better to have less custom JS in markdown pages and let custom components for `MdxRemote` decide what to do.

**Comment by Ehesp** [comment]
@lfades Thanks! It was [this comment](https://github.com/hashicorp/next-mdx-remote/issues/58#issuecomment-727668395) which made me wonder if it was possible.

As mentioned, the reason I'm using this PR is because it fixes an unrelated problem, the `export` thing was just curiosity!

That being said, is it possible to define local-only components within a single file? So a component which isn't exported/imported, but can only be created and used on the single page being rendered?

I'm toying around with an idea at the moment whereby the markdown provided is "unknown", so I am handling such errors as above. I'm just keen to understand if this PR allows for any additional functionality which I'm not aware of.

Cheers

**Comment by lfades** [comment]
@Ehesp I think it won't throw, although I'm not sure if it would be included in the output (MDX has some restrictions on that I think). Custom components is the way to go for your use case.

**Comment by trevorblades** [comment]
I was getting ``Prop `dangerouslySetInnerHTML` did not match.`` warnings in my console with the current active version of this package. I believe this had to do with a discrepancy between the way that Next server-renders pages vs. how `hydrate` was rendering the initial content on the client. Anyway, I can confirm that this PR fixes the issue! 🎉

**Comment by Ehesp** [comment]
@jescalan what are the plans for this PR? As far as I can tell it's working great.

**Comment by Ehesp** [comment]
Thought I'd have a play around with porting this code to TypeScript: https://github.com/Ehesp/next-mdx-remote

Seems to work, couldn't get Rollup working with the TSX file though.

**Comment by jescalan** [comment]
I do plan on getting this PR merged at some point, but am not in a huge rush to do so at the moment since it would require a large of testing and a very breaking release, and it does not close any major bugs with the library afaik. We will likely be taking a closer look at getting this across the line in January.

**Comment by BRKalow** [comment]
Thanks for your contribution here ❤️ 

Your approach is what ultimately drove the internal changes which were part of [v3](https://github.com/hashicorp/next-mdx-remote/releases/tag/3.0.0). Sorry it took so long, but thank you again!

**Pull request closed without merging**
