### PR TITLE
Feat: add `serializeSync`

### PR DESCRIPTION
**Pull request by aspeddro**

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
Before merge you should add docs on readme, what do you think

**Comment by aspeddro** [comment]
See https://github.com/hashicorp/next-mdx-remote/pull/392/commits/608b6b38ea6587231660522511c2de629e02884f

**Comment by BRKalow** [comment]
@aspeddro What's the specific use case for a sync method?

**Comment by aspeddro** [comment]
The flow was synchronous now it is no longer necessary

**Pull request closed without merging**
