### PR TITLE
Support Providers

### LINKED ISSUE #32: Question: Consuming an existing MDXProvider
> Possibly related to #10 and #9

I've been following the [`next-mdx-remote` example in Next.js repo](https://github.com/vercel/next.js/pull/16613/files) and have managed to successfully migrate my `next-mdx-enhanced` implementation content and rehypePlugins, **but** I'm really struggling to get it working with my existing `MDXProvider`

I'm using Theme-UI's ThemeProvider, which means a lot of my MDX components are consuming from the Theme Provider (which is nested inside this provider). Should I be passing something into `scope` to ensure my components are referencing my MDXProvider (and its nested ThemePovider)?

Would really appreciate any support on this!

### PR DESCRIPTION
**Pull request by jescalan**
This was a larger task than I originally imagined, but it is done, and thoroughly tested. Whoo!

Closes #32

### CODE REVIEW

**Comment by ynnoj** [comment]
@jescalan Thanks for pushing this along!

I've updated my implementation to use the new `provider` option for both `renderToString` and `hydrate` functions, however not seeing the behaviour I was expecting/hoping for.

Seems the component doesn't rehydrate on state change, in this case when a network call (to authenticate) resolves. `user` is always `null`.

Here is my [WIP PR](https://github.com/firstmeanseverything/next/pull/81). Perhaps this an implementation issue at my end, would love to understand more!

**Comment by molebox** [comment]
Hows this looking team?

**Comment by jescalan** [comment]
Hey @molebox it's on my radar. Are you interested in helping?

**Comment by molebox** [comment]
> Hey @molebox it's on my radar. Are you interested in helping?

Sorry for the late reply, sure, if i could help at all

**Comment by jescalan** [comment]
Ok - feel free to dive in to Jonathan's example above and see if you can debug it and find the problem. I don't want to ship until I am sure his case has been resolved.

**Comment by deckchairlabs** [comment]
Using this pull request, I don't think it does what I need it to. I believe I need an option where I can replace the `MDXProvider`

I'm having an issue where I am using `ThemeProvider` from the `theme-ui` package. Which allows styling of MDX content by passing the components to the `components` prop of the `ThemeProvider`

So this is what I'm doing currently, which isn't exactly right because the resulting tree would look like
`ThemeProvider -> MDXProvider -> MDXProvider -> MDXContent`
```js
const options = {
  components,
  provider: {
    component: ThemeProvider,
    props: {
      theme,
      components,
    },
  },
}
```

**Comment by jescalan** [comment]
@etienne-martin sure - see my comment above: https://github.com/hashicorp/next-mdx-remote/pull/35#issuecomment-693649735

I'm sorry this keeps getting pushed down my list, there's a lot going on at my job right now. I am still aware of this and want to get to it as soon as I am able.

**Comment by etienne-martin** [comment]
No worries!

I reviewed @ynnoj's implementation and I don't see anything wrong with it.

I'll try to make sense of the codebase.

**Comment by alfonmga** [comment]
I believe we should get this merged ASAP and free a lot of guys from the painful `next-mdx-enhanced` alternative. @ynnoj's issue could be tracked down in another PR and fix the possible hydration issue later.

Almost >90% of us need this PR to able to pass an `MDXProvider` not a [React Context Provider](https://reactjs.org/docs/context.html#contextprovider).

LGTM please I beg you :)

**Comment by jescalan** [comment]
@alfonmga This comment is way out of line, I'm sorry.

@ynnoj has posted above a very basic use case that is completely non-functional. Aside from the internal test, I have not yet heard from anyone who has taken the PR for a spin and produced a successful result. As such, I assume that some additional work is needed here to get things working correctly. I would like to not ship a broken feature. Have you tested this code and it works in your project, or are you assuming that the test case provided here is just an edge case?

Your arbitrary made up statistic is also entirely unhelpful.

If you would like to advance this initiative, _help out_. I have been really busy at work and just haven't had the bandwidth to prioritize this over the last several weeks. But the good news is that this is an open source project, which means that if you really need something the author is unable to prioritize for you, for free, you can step up and help to push it forward yourself. Another great alternative is that you can simply use this code in its current state in a variety of different ways, as you seem to be convinced that it works correctly and should just be merged. This will allow you to test it out and deliver feedback on whether its working as well. Just change your npm dependency from `next-mdx-remote` to `hashicorp/next-mdx-remote#devrsi0n-custom-provider` - that will tell npm to pull this branch's code for use in your project.

To you @alfonmga, and to everyone that upvoted his comment, it's time to do a little internal reflection, I think. Are you the type of developer who demands other people do work for you for free on an open source project? Are you the type of developer who "approves" a pull request and asks for it to be shipped without reviewing or testing the code? Or are you the type of developer who carefully tests and reviews code, and pitches in to help out with shared community problems? I genuinely hope that at least the goal is the latter 💖

**Comment by molebox** [comment]
> @alfonmga This comment is way out of line, I'm sorry.
> 
> @ynnoj has posted above a very basic use case that is completely non-functional. Aside from the internal test, I have not yet heard from anyone who has taken the PR for a spin and produced a successful result. As such, I assume that some additional work is needed here to get things working correctly. I would like to not ship a broken feature. Have you tested this code and it works in your project, or are you assuming that the test case provided here is just an edge case?
> 
> Your arbitrary made up statistic is also entirely unhelpful.
> 
> If you would like to advance this initiative, _help out_. I have been really busy at work and just haven't had the bandwidth to prioritize this over the last several weeks. But the good news is that this is an open source project, which means that if you really need something the author is unable to prioritize for you, for free, you can step up and help to push it forward yourself. Another great alternative is that you can simply use this code in its current state in a variety of different ways, as you seem to be convinced that it works correctly and should just be merged. This will allow you to test it out and deliver feedback on whether its working as well. Just change your npm dependency from `next-mdx-remote` to `hashicorp/next-mdx-remote#devrsi0n-custom-provider` - that will tell npm to pull this branch's code for use in your project.
> 
> To you @alfonmga, and to everyone that upvoted his comment, it's time to do a little internal reflection, I think. Are you the type of developer who demands other people do work for you for free on an open source project? Are you the type of developer who "approves" a pull request and asks for it to be shipped without reviewing or testing the code? Or are you the type of developer who carefully tests and reviews code, and pitches in to help out with shared community problems? I genuinely hope that at least the goal is the latter 💖

I upvoted, on my phone while travelling somewhere as i agreed with the sentiment of "lets get this finished". However I have not taken this for a spin, nor have I tried to help out in anyway. I feel bad having read your comment and I retract my upvote. I contribute to open source and also have many packages that i try and keep up to date (regardless of how many people use them)

I apologies and you are totally right. Im going to set aside some time this weekend and try this PR out and see how it behaves. Will report back.

**Comment by mattboon** [comment]
Have tried out this branch, thanks for the work on this.

The new `provider` prop seems to work as expected to add the styled-components `<ThemeProvider>` and allowing use of dynamic theme variables:

```js
const Heading = styled.h1`
  ${color}
  padding: ${props => props.theme.space[4]};
`

export const components = {
  h1: props => <Heading color="primary" {...props} />
}

const mdxSource = await renderToString(content, {
  components,
  provider: {
    component: props => <ThemeProvider {...props} theme={theme} />,
  },
})

const content = hydrate(source, {
  components,
  provider: {
    component: props => <ThemeProvider {...props} theme={theme} />,
  },
})
```

Actually, I found could accomplish essentially the same thing on the `master` branch by using the `wrapper` key in the `components` object, which seems to wrap markdown content before rendering

```js
export const components = {
  wrapper: props => <ThemeProvider {...props} theme={theme} />,
  h1: props => <Heading color="primary" {...props} />
}

const mdxSource = await renderToString(content, components)

const content = hydrate(source, components)
```

I guess this will only work safely if you don't have an export in your MDX file, for example:

```md
export default ({ children }) => <Layout>{children}</Layout>
```
---

#### Collecting `styled-components` during SSR?

There is one issue, though not sure if it relates directly to this PR?
I still see the flash of un-styled HTML from the server-render, before the client hydration kicks in.

The class names **are** being generated by the `renderToString()` function and served via SSR

```tml
<h1 class="sc-gXZlrW jtSabM">Hello world</h1>
```

However the styles **are not** included/rendered into the `<head>` via styled-components

I am assuming it's because the styles collection in `_document.ts` does not find the components from server render?

```js
sheet.collectStyles(<App {...props} />)
```

If anyone has any ideas to solve this, would be much appreciated!

**Comment by cadbox1** [comment]
thanks @mattboon, I was able to get my theme-ui theme working with the wrapper as well: [https://github.com/cadbox1/cadell-nextjs-blog-starter](https://github.com/cadbox1/cadell-nextjs-blog-starter)

**Comment by BRKalow** [comment]
Hey y'all, this should be good to go 🤞 

@ynnoj I realize we're a few months down the road here, but if you do get a chance to try out the latest updates it would be much appreciated! I tried to pull down your PR, but am missing some required env vars 😄

For those of you using `theme-ui`, from what I can tell the `MDXProvider` should respect the themed components and pass them along, but it's something we can look deeper into if it's not working quite right. Any help here would be appreciated as we don't have direct experience with the package!

@mattboon Regarding your question on `styled-components` and SSR, I have some ideas on how this might work, but it will definitely require some `styled-components` specific plumbing. I'll try to carve out some time to do some testing and report back. That being said, let us know if you've made further progress and we can update the docs!

**Comment by ynnoj** [comment]
Nice! This is working excellent as I need now.

Great work pushing this through @BRKalow & @jescalan ❤️

**Comment by jescalan** [comment]
✅ approved - we should have a release out today!

**Pull request merged**
